import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


export default function Home({products}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
        {products.data.length? products.data.map((product)=>{
        return (
            <div key={product.id}>
            <div>{product.name}</div>
            <div>{product.price}</div>
            <Link href={`scooter/${product.category_name}`} passHref><a >{product.category_name}</a></Link>
            </div>
            )
          }):
        (<p></p>)
        }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  // Call an external API endpoint to get posts
  //local
  // const res = await fetch('http://127.0.0.1:8000/api/getProducts')
  
  // server
  const res = await fetch('http://scooterpanel.ranazain.com/api/getProducts')

  const products   = await res.json();
  // const posts   = res;

  // console.log("hello world");
  // console.log(products);

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      // posts: posts.slice(0,3),
      products: products,
    },
    // revalidate: 10,
  }
}

